"""ajuste AccessLog

Revision ID: 6182be9cecfb
Revises: 2c16abc15b56
Create Date: 2026-05-05 15:28:23.705634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6182be9cecfb'
down_revision = '2c16abc15b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.alter_column('attempted__user',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlocked_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('desbloqueio_em')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desbloqueio_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('unlocked_at')

    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.alter_column('attempted__user',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
