"""remoção de campo extra

Revision ID: 62c68b06ccba
Revises: 6182be9cecfb
Create Date: 2026-05-06 22:49:50.601511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62c68b06ccba'
down_revision = '6182be9cecfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('type_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_user', postgresql.ENUM('Estudante', 'Professor(a)', 'Outro(a)', name='usertype'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
