"""configuracao inicial

Revision ID: f0d4d8f06ef3
Revises: 
Create Date: 2026-05-01 10:35:06.900593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d4d8f06ef3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('use_id', sa.UUID(), nullable=False),
    sa.Column('ra', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=255), nullable=False),
    sa.Column('rg', sa.String(length=255), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.Column('marital', sa.String(length=30), nullable=True),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('profile', sa.Enum('Coordenador(a)', 'Admin', 'Voluntário(a)', name='userprofile'), nullable=False),
    sa.Column('status', sa.Enum('Ativo', 'Desligado', 'Excluído', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('use_id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('ra')
    )
    op.create_table('access_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.use_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('postal_code', sa.String(length=8), nullable=False),
    sa.Column('street', sa.String(length=150), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.use_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_recovery_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.use_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.Enum('Ativa', 'Desligada', 'Excluída', name='userstatus'), nullable=False),
    sa.Column('new_status', sa.Enum('Ativa', 'Desligada', 'Excluída', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.use_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.use_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(), nullable=False),
    sa.Column('desbloqueio_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.use_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_blocks')
    op.drop_table('status_history')
    op.drop_table('password_recovery_tokens')
    op.drop_table('address')
    op.drop_table('access_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
