"""atualização do campo senha

Revision ID: 272b26ec680b
Revises: 6055fbd25aa2
Create Date: 2026-05-01 15:23:47.348766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272b26ec680b'
down_revision = '6055fbd25aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password', new_column_name='password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash', new_column_name='password')

    # ### end Alembic commands ###
