"""refec_AccessLog

Revision ID: 2c16abc15b56
Revises: 272b26ec680b
Create Date: 2026-05-04 21:42:10.039010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c16abc15b56'
down_revision = '272b26ec680b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    usertype = sa.Enum('Estudante', 'Professor(a)', 'Outro(a)', name='usertype')
    usertype.create(op.get_bind())
    
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempted__user', sa.String(length=20), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_user', sa.Enum('Estudante', 'Professor(a)', 'Outro(a)', name='usertype'), nullable=False))
        batch_op.add_column(sa.Column('code_institutional', sa.String(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('users_ra_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['code_institutional'])
        batch_op.drop_column('ra')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ra', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('users_ra_key'), ['ra'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('code_institutional')
        batch_op.drop_column('type_user')

    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('attempted__user')

    sa.Enum(name='usertype').drop(op.get_bind())
    # ### end Alembic commands ###
