"""correcao do ra para unico

Revision ID: 32257be55206
Revises: f0d4d8f06ef3
Create Date: 2026-05-01 11:02:19.197659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32257be55206'
down_revision = 'f0d4d8f06ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['rg'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
