"""updateUser

Revision ID: b0698be47c2d
Revises: 7c76967dc8ed
Create Date: 2026-06-19 17:53:51.195817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0698be47c2d'
down_revision = '7c76967dc8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    usersector = sa.Enum('Marketing', 'Recursos Humanos', 'Conteúdo', 'Instrutor', name='usersector')
    userposition = sa.Enum('Coordenador(a) estudantil', 'Representante do setor', 'Voluntário(a)', name='userposition')
    
    with op.batch_alter_table('users', schema=None) as batch_op:
           
        usersector.create(op.get_bind(), checkfirst=True)
        userposition.create(op.get_bind(), checkfirst=True)
        batch_op.add_column(sa.Column('sector', sa.Enum('Marketing', 'Recursos Humanos', 'Conteúdo', 'Instrutor', name='usersector'), nullable=True))
        batch_op.add_column(sa.Column('position', sa.Enum('Coordenador(a) estudantil', 'Representante do setor', 'Voluntário(a)', name='userposition'), nullable=True))
        batch_op.add_column(sa.Column('entry_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('departure_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('update_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('departure_at')
        batch_op.drop_column('entry_at')
        batch_op.drop_column('position')
        batch_op.drop_column('sector')
        
        sa.Enum(name='userposition').drop(op.get_bind())
        sa.Enum(name='usersector').drop(op.get_bind())

    # ### end Alembic commands ###
